spring:
  application:
    name: config-server
  rabbitmq:
    host: 192.168.17.132
    port: 5672
    username: admin
    password: admin

  profiles:
    active: native
    
#  cloud: 默认配置
#    config:
#      server:
#        native:
#          search-locations: classpath:/config
#        git:
#          uri: https://github.com/SirCsj/sp_repo
#          searchPaths: sp-config
          #username: your-username
          #password: your-password
    
server:
  port: 6001
    
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh